### ISSUE TITLE
User can find a course to play.

### ISSUE THREAD

**Issue by riley-rangel** [riley-rangel/birdie-backup#1]
# Motivation 👍 
This feature is vitally important to the core functionality of the app. Users will need to be able to browse golf courses available and find the right one to play for their individual needs.

# Implementation 🛠 
- [x] Create mock feature design on myBalsamiq and add to GitHub issue.
- [x] Checkout new branch for issue-1
- [x] Create index.html, styles.css and main.js for project.
- [x] Link documents and Materialize framework.
- [x] Prepare golf course data model.
- [x] Set up header and footer elements.
- [x] Add placeholder for logo and text on header.
- [x] Add sample box to sample html that will need to be rendered.
- [x] Build rendering function for course display.
- [x] Remove node_modules files
- [x] Add, commit and push local files to remote.
- [x] Open pull request to 'master' branch (if no issues).
- [x] Merge to 'master' branch.

![birdiebackupmock1](https://user-images.githubusercontent.com/31449041/30345663-d6703188-97ba-11e7-8d46-0b4ed2a9ccfa.png)

**Comment by thebearingedge** [comment]
Great wire frame!
